***Perform other matrix operations like converting matrix data to absolute values, taking the neagative of matrix values, additing/removing rows/columns from a matrix, finding the maximum or minimum values in a matrix or in a row/column, and finding the sum of some/all elements in a matrix***

In [1]:
import numpy as np

# Define a matrix
matrix = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])

# Convert matrix data to absolute values
abs_matrix = np.abs(matrix)

# Take the negative of matrix values
neg_matrix = -matrix

# Adding a row to the matrix
new_row = np.array([10, -11, 12])
matrix_with_row_added = np.vstack([matrix, new_row])

# Removing a row from the matrix
matrix_with_row_removed = np.delete(matrix, 1, axis=0)  # Removing the second row (index 1)

# Adding a column to the matrix
new_column = np.array([10, -11, 12])
matrix_with_column_added = np.hstack([matrix, np.atleast_2d(new_column).T])

# Removing a column from the matrix
matrix_with_column_removed = np.delete(matrix, 1, axis=1)  # Removing the second column (index 1)

# Finding maximum and minimum values in the matrix
max_value = np.max(matrix)
min_value = np.min(matrix)

# Finding maximum and minimum values in a row or column
max_value_row = np.max(matrix, axis=1)  # Maximum value in each row
min_value_column = np.min(matrix, axis=0)  # Minimum value in each column

# Finding the sum of all elements in the matrix
total_sum = np.sum(matrix)

# Display results
print("Absolute Values of Matrix:")
print(abs_matrix)

print("\nNegative of Matrix Values:")
print(neg_matrix)

print("\nMatrix with Row Added:")
print(matrix_with_row_added)

print("\nMatrix with Row Removed:")
print(matrix_with_row_removed)

print("\nMatrix with Column Added:")
print(matrix_with_column_added)

print("\nMatrix with Column Removed:")
print(matrix_with_column_removed)

print("\nMaximum Value in Matrix:", max_value)
print("Minimum Value in Matrix:", min_value)

print("\nMaximum Value in Each Row:", max_value_row)
print("Minimum Value in Each Column:", min_value_column)

print("\nTotal Sum of Matrix Elements:", total_sum)


Absolute Values of Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Negative of Matrix Values:
[[-1  2 -3]
 [ 4 -5  6]
 [-7  8 -9]]

Matrix with Row Added:
[[  1  -2   3]
 [ -4   5  -6]
 [  7  -8   9]
 [ 10 -11  12]]

Matrix with Row Removed:
[[ 1 -2  3]
 [ 7 -8  9]]

Matrix with Column Added:
[[  1  -2   3  10]
 [ -4   5  -6 -11]
 [  7  -8   9  12]]

Matrix with Column Removed:
[[ 1  3]
 [-4 -6]
 [ 7  9]]

Maximum Value in Matrix: 9
Minimum Value in Matrix: -8

Maximum Value in Each Row: [3 5 9]
Minimum Value in Each Column: [-4 -8 -6]

Total Sum of Matrix Elements: 5
