***Perform vectorized of simple matrix operation like finding the transpose of a matrix, adding,subtracting or multiplying two matrices***

In [1]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])

matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Transpose of a matrix
transpose_matrix1 = np.transpose(matrix1)

# Addition of matrices
matrix_addition = matrix1 + matrix2

# Subtraction of matrices
matrix_subtraction = matrix1 - matrix2

# Multiplication of matrices
matrix_multiplication = np.dot(matrix1, matrix2)

# Display results
print("Original Matrix:")
print(matrix1)

print("\nTranspose of Matrix:")
print(transpose_matrix1)

print("\nAddition of Matrices:")
print(matrix_addition)

print("\nSubtraction of Matrices:")
print(matrix_subtraction)

print("\nMultiplication of Matrices:")
print(matrix_multiplication)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Addition of Matrices:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of Matrices:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Multiplication of Matrices:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
