***Perform basic operations on matrices (like addition, subtraction, multiplication) and display specific rows or columns of the matrix***

In [1]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Addition of matrices
matrix_addition = matrix1 + matrix2

# Subtraction of matrices
matrix_subtraction = matrix1 - matrix2

# Multiplication of matrices
matrix_multiplication = np.dot(matrix1, matrix2)

# Display specific rows or columns of a matrix
specific_row = matrix1[1]  # Displaying the second row (index 1)
specific_column = matrix1[:, 2]  # Displaying the third column (index 2)

# Display results
print("Matrix Addition:")
print(matrix_addition)

print("\nMatrix Subtraction:")
print(matrix_subtraction)

print("\nMatrix Multiplication:")
print(matrix_multiplication)

print("\nSpecific Row (Index 1):")
print(specific_row)

print("\nSpecific Column (Index 2):")
print(specific_column)


Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Specific Row (Index 1):
[4 5 6]

Specific Column (Index 2):
[3 6 9]
