***Create/Define single dimension/multi-dimension arrays, and arrays with specific values like array of all ones, all zeros, array with random values within a range, or a diagonal matrix.***

In [1]:
import numpy as np

# Define single-dimensional array
single_dimension_array = np.array([1, 2, 3, 4, 5])

# Define multi-dimensional array
multi_dimension_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Array of all ones
ones_array = np.ones((3, 3))  # A 3x3 array filled with ones

# Array of all zeros
zeros_array = np.zeros((2, 4))  # A 2x4 array filled with zeros

# Array with random values within a range
random_array = np.random.randint(0, 10, size=(3, 3))  # A 3x3 array with random values between 0 and 10

# Diagonal matrix
diagonal_matrix = np.diag([1, 2, 3, 4, 5])  # A diagonal matrix with diagonal elements 1, 2, 3, 4, 5

# Display arrays
print("Single-dimensional array:")
print(single_dimension_array)

print("\nMulti-dimensional array:")
print(multi_dimension_array)

print("\nArray of all ones:")
print(ones_array)

print("\nArray of all zeros:")
print(zeros_array)

print("\nArray with random values within a range:")
print(random_array)

print("\nDiagonal matrix:")
print(diagonal_matrix)


Single-dimensional array:
[1 2 3 4 5]

Multi-dimensional array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array of all ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array of all zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array with random values within a range:
[[3 0 4]
 [8 3 8]
 [5 3 4]]

Diagonal matrix:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
